#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "**** Setup complete, starting Apache ****"

# Apache env (APACHE_RUN_USER/GROUP) is written into /etc/apache2/envvars by the
# init-bs-config one-shot service, based on whether PUID/PGID were provided.
# The master runs as root so it can bind port 80, then drops workers to that user.
. /etc/apache2/envvars

exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "nc -z localhost 80" \
    apache2 -DFOREGROUND
